### ISSUE TITLE
Anmerkungen

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [geoboxag/GEOBOX.OSC.DHM.Tools.Cutter#1]
Sehr flottes Programm, aber die Bedienung ist "ungewöhnlich" - JSON Anpassung ohne Menü, ohne Fehlerbehandlung, .. ist nicht jedermanns Sache. Das ist noch ausbaubar ..

**Comment by urss1** [comment]
Besten Dank für die Rückmeldung.
Wenn Sie uns beim Ausbau behilflich sein möchten, bitte wir Sie mit uns Kontakt aufzunehmen.

**Comment by Pierre-de-la-Verre** [comment]
Für Programmierungsaspekte fehlen mir die Kenntnisse, aber ich kann - wenn gewollt - Hinweise aus Anwendersicht geben.
